name = "google-calendar-worker"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

[[kv_namespaces]]
binding = "KV_GCP_SERVICE_ACCOUNT"
id = "YOUR_NAMESPACE_ID"
preview_id = "YOUR_PREVIEW_NAMESPACE_ID"
